"use client"
// import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { useSession } from "next-auth/react";
import { useEffect } from "react";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@/lib/userContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${outfit.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// function AuthSync() {
//     const { data: session } = useSession();
//     useEffect(() => {
//         if ((session as any)?.accessToken) {
//             localStorage.setItem("accessToken", (session as any).accessToken);
//         }
//     }, [session]);
//     return null;
// }

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <html lang="en">
//             <body className={`${outfit.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
//                 <SessionProvider basePath="/api/nextauth">
//                     {children}
//                 </SessionProvider>
//             </body>
//         </html>
//     );
// }
function AuthSync() {
    const { data: session, status } = useSession();
    useEffect(() => {
        if (status === "loading") return;

        // If signed in through oauth, store tokens to where they belong
        if (session) {
            
            localStorage.removeItem("accessToken");
            localStorage.removeItem("user");
            
            if ((session as any)?.accessToken) {
                localStorage.setItem("accessToken", (session as any).accessToken);
                window.dispatchEvent(new Event("auth-change"));
            }
            if ((session as any)?.refreshToken) {
                document.cookie = `refreshToken=${(session as any).refreshToken}; path=/; max-age=${7 * 24 * 60 * 60}`;
            }
        }
    }, [session, status]);
    return null;
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${outfit.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
                <SessionProvider basePath="/api/nextauth">
                <UserProvider>
                    <AuthSync />
                    <Navbar />
                    {children}
                </UserProvider>
                </SessionProvider>
            </body>
        </html>
    );
}